{% set name = "graphene-django" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphene-django-{{ version }}.tar.gz
  sha256: d831bfe8e9a6e77e477b7854faef4addb318f386119a69ee4c57b74560f3e07d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
  run:
    - django-filter
    - djangorestframework
    - python >={{ python_min }}
    - graphene >=3.0,<4
    - graphql-core >=3.1.0,<4
    - graphql-relay >=3.1.1,<4
    - django >=3.2
    - promise >=2.1
    - text-unidecode

test:
  imports:
    - graphene_django
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/graphql-python/graphene-django
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Django integration
  description: Graphene-Django is built on top of Graphene. Graphene-Django provides some additional abstractions that make it easy to add GraphQL functionality to your Django project.
  doc_url: https://docs.graphene-python.org/projects/django/en/latest/
  dev_url: https://github.com/graphql-python/graphene-django

extra:
  recipe-maintainers:
    - rxm7706
    - KingDarBoja
